name: Waka update

on:
  workflow_dispatch:
  schedule:
    # Runs six hours
    - cron: "* 6 * * *"

jobs:
  update-readme:
    name: Update my README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          TIME_RANGE: last_10_days
          COMMIT_MESSAGE: Updated Waka stats in README
          SHOW_TOTAL: true
          SHOW_TIME: true